### PR TITLE
Allow array of expressions in dimension filters

### PR DESCRIPTION
**Pull request by elanclarkson**
Hi there - just wanted to say thanks very much for creating this package! It really is an easy and simple solution to interfacing with Google's latest v4 API.

I've just made a minor adjustment for my use case, which is to remove the type hinting for the expression parameter when setting the dimension filter, thus enabling us to optionally pass an array for filtering with the 'IN_LIST' operator.  

More info here: https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#DimensionFilterClause

### CODE REVIEW

**Comment by panakour** [comment]
@elanclarkson Thank you very much for your PR. It would be really helpful if you can update the [README](https://github.com/panakour/google-analytics/blob/master/README.md#usage) with one use case using `IN_LIST` operator.

**Comment by panakour** [comment]
Let me know if you have the time to update the readme so as I wait for it before I merge your PR.

**Comment by elanclarkson** [comment]
@panakour sorry for the delay, was really busy on this project. I have updated the README. :)

**Comment by panakour** [comment]
Thanks

**Pull request merged**
